name: CI

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install cargo-spellcheck
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-spellcheck
          fallback: none

      - name: Install taplo
        uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli

      - name: Run CI
        run: just ci
